name: Tests On Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    uses: ./.github/workflows/pytest-workflow-call.yaml
    permissions:
      contents: read
  static-type-check:
    uses: ./.github/workflows/static-type-check-workflow-call.yaml
    permissions:
      contents: read
  code-style-check:
    uses: ./.github/workflows/code-style-check-workflow-call.yaml
    permissions:
      contents: read
